development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url:  redis://redistogo:f6825f85461e8278ddc0e8e748dd236a@soapfish.redistogo.com:9827/
  channel_prefix: GoalFunder_production
